In [119]:
import pandas as pd
df = pd.read_csv("Mobile_Dataset.csv")

In [200]:
# 1. Show first 5 rows
df.head(5)
# 2. Show last 10 rows
df.tail(10)
# 3. Find total rows and columns
df.shape
# 4. Show all column names
df.columns
# 5. Check datatype of each column
df.dtypes
# 6. Find missing values
df.isnull().sum()
# 7. Find duplicate rows
df[df.duplicated()]
# 8. Count unique companies
df["Company Name"].unique()

<StringArray>
[   'Apple',  'Samsung',  'OnePlus',     'Vivo',     'iQOO',     'Oppo',
   'Realme',   'Xiaomi',   'Lenovo', 'Motorola',   'Huawei',    'Nokia',
     'Sony',   'Google',    'Tecno',  'Infinix',    'Honor',     'POCO',
     'Poco']
Length: 19, dtype: str

In [201]:
df.columns

Index(['Unnamed: 0', 'Company Name', 'Model Name', 'Mobile Weight', 'RAM',
       'Front Camera', 'Back Camera', 'Processor', 'Battery Capacity',
       'Screen Size', 'Launched Price (Pakistan)', 'Launched Price (India)',
       'Launched Price (China)', 'Launched Price (USA)',
       'Launched Price (Dubai)', 'Launched Year'],
      dtype='str')

In [202]:
# Find all phones launched in 2023.
df[df["Launched Year"]==2023]

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
12,12,Apple,iPhone 15 128GB,171g,6GB,12MP,48MP,A16 Bionic,3200,6.1,"PKR 204,999","INR 74,999","CNY 5,299",USD 799,"AED 2,699",2023
13,13,Apple,iPhone 15 256GB,171g,6GB,12MP,48MP,A16 Bionic,3200,6.1,"PKR 214,999","INR 79,999","CNY 5,599",USD 849,"AED 2,999",2023
14,14,Apple,iPhone 15 512GB,171g,6GB,12MP,48MP,A16 Bionic,3200,6.1,"PKR 224,999","INR 89,999","CNY 5,999",USD 949,"AED 3,199",2023
15,15,Apple,iPhone 15 Plus 128GB,203g,6GB,12MP,48MP,A16 Bionic,4300,6.1,"PKR 234,999","INR 84,999","CNY 5,699",USD 899,"AED 3,199",2023
16,16,Apple,iPhone 15 Plus 256GB,203g,6GB,12MP,48MP,A16 Bionic,4300,6.1,"PKR 244,999","INR 94,999","CNY 6,199",USD 999,"AED 3,399",2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912,912,POCO,F5 Pro 256GB,204g,8GB,20MP,64MP,Snapdragon 8+ Gen 1,5160,6.1,"PKR 99,999","INR 39,999","CNY 3,299",USD 499,"AED 1,899",2023
913,913,POCO,X5 128GB,189g,6GB,13MP,48MP,Snapdragon 695,5000,6.1,"PKR 54,999","INR 18,999","CNY 1,799",USD 279,"AED 1,099",2023
914,914,POCO,X5 Pro 128GB,181g,6GB,16MP,108MP,Snapdragon 778G,5000,6.1,"PKR 64,999","INR 22,999","CNY 2,199",USD 329,"AED 1,199",2023
915,915,POCO,M6 64GB,199g,4GB,8MP,50MP,MediaTek Helio G88,5000,6.1,"PKR 29,999","INR 12,999","CNY 1,299",USD 199,AED 799,2023
916,916,POCO,M6 Pro 128GB,202g,6GB,8MP,50MP,Snapdragon 4 Gen 1,5000,6.1,"PKR 34,999","INR 14,999","CNY 1,499",USD 219,AED 849,2023

In [203]:
# Find all Samsung phones.
df[df["Company Name"] == "Samsung"]

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
97,97,Samsung,Galaxy S24 Ultra 128GB,234g,12GB,12MP,200MP + 12MP,Exynos 2400,5000,6.1,"PKR 450,000","INR 104,900","CNY 7,499","USD 1,199","AED 4,899",2024
98,98,Samsung,Galaxy S24 Ultra 256GB,234g,12GB,12MP,200MP + 12MP,Exynos 2400,5000,6.1,"PKR 480,000","INR 114,900","CNY 7,999","USD 1,299","AED 5,099",2024
99,99,Samsung,Galaxy S24+ 128GB,196g,8GB,12MP,50MP + 12MP,Exynos 2400,4800,6.1,"PKR 400,000","INR 89,900","CNY 6,199",USD 899,"AED 3,599",2024
100,100,Samsung,Galaxy S24+ 256GB,196g,8GB,12MP,50MP + 12MP,Exynos 2400,4800,6.1,"PKR 430,000","INR 99,900","CNY 6,999",USD 999,"AED 3,799",2024
101,101,Samsung,Galaxy S24 128GB,168g,8GB,12MP,50MP + 12MP,Exynos 2400,4000,6.1,"PKR 350,000","INR 79,900","CNY 5,799",USD 799,"AED 3,299",2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,180,Samsung,Galaxy Tab E 10.1 16GB,490g,1.5GB,2MP,5MP,Spreadtrum SC8830,5000,6.1,"PKR 35,000","INR 9,999",CNY 899,USD 129,AED 499,2016
181,181,Samsung,Galaxy Tab E 8.0 16GB,360g,1.5GB,2MP,5MP,Qualcomm MSM8916,5000,6.1,"PKR 28,000","INR 8,499",CNY 799,USD 99,AED 399,2016
927,927,Samsung,Galaxy Z Fold6 256GB,239g,12GB,"10MP, 4MP (UDC)",50MP,Snapdragon 8 Gen 3,4400,6.1,"PKR 604,999","INR 164,999","Â¥13,999","USD 1,899","AED 7,199",2024
928,928,Samsung,Galaxy Z Fold6 512GB,239g,12GB,"10MP, 4MP (UDC)",50MP,Snapdragon 8 Gen 3,4400,6.1,"PKR 544,999","INR 176,999","CNY 15,999",USD 1719,"AED 7,699",2024
929,929,Samsung,Galaxy Z Fold6 1TB,239g,12GB,"10MP, 4MP (UDC)",50MP,Snapdragon 8 Gen 3,4400,6.1,Not available,"INR 200,999","CNY 17,999Â","USD 2,259","AED 8,699",2024

In [204]:
# Find all Xiaomi phones.
df[df["Company Name"] == "Xiaomi"]

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
522,522,Xiaomi,Xiaomi 15 Pro 256GB,210g,12GB,32MP,50MP (Main) + 50MP (Ultra-wide) + 50MP (Teleph...,Snapdragon 8 Elite,6100,6.1,"PKR 199,999","INR 89,999","CNY 5,299",USD 799,"AED 3,299",2024
523,523,Xiaomi,Xiaomi 15 Pro 512GB,210g,16GB,32MP,50MP (Main) + 50MP (Ultra-wide) + 50MP (Teleph...,Snapdragon 8 Elite,6100,6.1,"PKR 219,999","INR 99,999","CNY 5,799",USD 899,"AED 3,699",2024
524,524,Xiaomi,Xiaomi 15 Pro 1TB,210g,16GB,32MP,50MP (Main) + 50MP (Ultra-wide) + 50MP (Teleph...,Snapdragon 8 Elite,6100,6.1,"PKR 239,999","INR 109,999","CNY 6,499",USD 999,"AED 4,099",2024
525,525,Xiaomi,Xiaomi 15 256GB,190g,12GB,32MP,50MP (Main) + 50MP (Ultra-wide),Snapdragon 8 Elite,5400,6.1,"PKR 179,999","INR 79,999","CNY 4,299",USD 699,"AED 2,899",2024
526,526,Xiaomi,Xiaomi 15 512GB,190g,16GB,32MP,50MP (Main) + 50MP (Ultra-wide),Snapdragon 8 Elite,5400,6.1,"PKR 199,999","INR 89,999","CNY 4,799",USD 799,"AED 3,299",2024
527,527,Xiaomi,Xiaomi 14T Pro 256GB,209g,12GB,32MP,50MP (Main) + 50MP (Ultra-wide) + 50MP (Teleph...,Dimensity 9300+,5000,6.1,"PKR 169,999","INR 74,999","CNY 3,999",USD 634.99,"AED 2,699",2024
528,528,Xiaomi,Xiaomi 14T Pro 512GB,209g,12GB,32MP,50MP (Main) + 50MP (Ultra-wide) + 50MP (Teleph...,Dimensity 9300+,5000,6.1,"PKR 189,999","INR 84,999","CNY 4,299",USD 790.77,"AED 2,999",2024
529,529,Xiaomi,Xiaomi 14T Pro 1TB,209g,12GB,32MP,50MP (Main) + 50MP (Ultra-wide) + 50MP (Teleph...,Dimensity 9300+,5000,6.1,"PKR 209,999","INR 94,999","CNY 4,799",USD 899,"AED 3,299",2024
530,530,Xiaomi,Xiaomi 14T 256GB,195g,12GB,32MP,50MP (Main) + 50MP (Ultra-wide),Dimensity 8300-Ultra,5000,6.1,"PKR 149,999","INR 69,999","CNY 3,499",USD 599,"AED 2,499",2024
531,531,Xiaomi,Xiaomi 14T 512GB,195g,12GB,32MP,50MP (Main) + 50MP (Ultra-wide),Dimensity 8300-Ultra,5000,6.1,"PKR 169,999","INR 79,999","CNY 3,799",USD 699,"AED 2,799",2024
532,532,Xiaomi,Xiaomi 14 Pro 256GB,206g,12GB,32MP,50MP (Main) + 50MP (Ultra-wide) + 50MP (Teleph...,Snapdragon 8 Gen 3,5000,6.1,"PKR 189,999","INR 84,999","CNY 4,799",USD 799,"AED 3,299",2023
533,533,Xiaomi,Xiaomi 14 Pro 512GB,206g,12GB,32MP,50MP (Main) + 50MP (Ultra-wide) + 50MP (Teleph...,Snapdragon 8 Gen 3,5000,6.1,"PKR 209,999","INR 94,999","CNY 5,299",USD 899,"AED 3,699",2023
534,534,Xiaomi,Xiaomi 14 256GB,189g,12GB,32MP,50MP (Main) + 50MP (Ultra-wide),Snapdragon 8 Gen 3,4610,6.1,"PKR 169,999","INR 74,999","CNY 3,999",USD 699,"AED 2,899",2023
535,535,Xiaomi,Xiaomi 14 512GB,189g,12GB,32MP,50MP (Main) + 50MP (Ultra-wide),Snapdragon 8 Gen 3,4610,6.1,"PKR 189,999","INR 84,999","CNY 4,499",USD 799,"AED 3,299",2023
536,536,Xiaomi,Redmi Note 14 Pro+ 5G 128GB,205g,8GB,16MP,200MP (Main) + 8MP (Ultra-wide) + 2MP (Macro),Snapdragon 7s Gen 3,5110,6.1,"PKR 89,999","INR 29,999","CNY 2,499",USD 374.90,"AED 1,499",2024
537,537,Xiaomi,Redmi Note 14 Pro+ 5G 256GB,205g,12GB,16MP,200MP (Main) + 8MP (Ultra-wide) + 2MP (Macro),Snapdragon 7s Gen 3,5110,6.1,"PKR 99,999","INR 32,999","CNY 2,799",USD 399.00,"AED 1,599",2024
538,538,Xiaomi,Redmi Note 14 Pro+ 5G 512GB,205g,16GB,16MP,200MP (Main) + 8MP (Ultra-wide) + 2MP (Macro),Snapdragon 7s Gen 3,5110,6.1,"PKR 109,999","INR 35,999","CNY 3,099",USD 429.00,"AED 1,699",2024
539,539,Xiaomi,Redmi Note 14 Pro 5G 128GB,195g,8GB,16MP,108MP (Main) + 8MP (Ultra-wide) + 2MP (Macro),MediaTek Dimensity 7300-Ultra,5500,6.1,"PKR 79,999","INR 27,999","CNY 2,199",USD 349.00,"AED 1,399",2024
540,540,Xiaomi,Redmi Note 14 Pro 5G 256GB,195g,12GB,16MP,108MP (Main) + 8MP (Ultra-wide) + 2MP (Macro),MediaTek Dimensity 7300-Ultra,5500,6.1,"PKR 89,999","INR 30,999","CNY 2,499",USD 379.00,"AED 1,499",2024
541,541,Xiaomi,Redmi Note 14 Pro 4G 128GB,190g,6GB,16MP,108MP (Main) + 8MP (Ultra-wide) + 2MP (Macro),Qualcomm Snapdragon 732G,5000,6.1,"PKR 69,999","INR 24,999","CNY 1,999",USD 299.00,"AED 1,199",2024
542,542,Xiaomi,Redmi Note 14 Pro 4G 256GB,190g,8GB,16MP,108MP (Main) + 8MP (Ultra-wide) + 2MP (Macro),Qualcomm Snapdragon 732G,5000,6.1,"PKR 79,999","INR 27,999","CNY 2,299",USD 329.00,"AED 1,299",2024
543,543,Xiaomi,Redmi Note 14 5G 128GB,185g,6GB,16MP,50MP (Main) + 8MP (Ultra-wide) + 2MP (Macro),MediaTek Dimensity 7025-Ultra,5000,6.1,"PKR 59,999","INR 21,999","CNY 1,799",USD 279.00,"AED 1,099",2024
544,544,Xiaomi,Redmi Note 14 5G 256GB,185g,8GB,16MP,50MP (Main) + 8MP (Ultra-wide) + 2MP (Macro),MediaTek Dimensity 7025-Ultra,5000,6.1,"PKR 69,999","INR 24,999","CNY 2,099",USD 309.00,"AED 1,199",2024
545,545,Xiaomi,Redmi Note 14 4G 128GB,180g,4GB,16MP,50MP (Main) + 8MP (Ultra-wide) + 2MP (Macro),Qualcomm Snapdragon 680,5000,6.1,"PKR 49,999","INR 18,999","CNY 1,599",USD 249.00,AED 999,2024
546,546,Xiaomi,Redmi Note 14 4G 256GB,180g,6GB,16MP,50MP (Main) + 8MP (Ultra-wide) + 2MP (Macro),Qualcomm Snapdragon 680,5000,6.1,"PKR 59,999","INR 21,999","CNY 1,899",USD 279.00,"AED 1,099",2024
547,547,Xiaomi,Redmi 14C 5G 64GB,195g,4GB,8MP,50MP (Main) + 2MP (Depth),MediaTek Dimensity 700,5000,6.1,"PKR 39,999","INR 14,999","CNY 1,299",USD 199.00,AED 799,2024
548,548,Xiaomi,Redmi 14C 5G 128GB,195g,6GB,8MP,50MP (Main) + 2MP (Depth),MediaTek Dimensity 700,5000,6.1,"PKR 44,999","INR 16,999","CNY 1,499",USD 229.00,AED 899,2024

In [213]:
# Find phones with battery greater than 5000 mAh.
df[df["Battery Capacity"]>5000]

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
80,80,Apple,iPad Air 10.9-inch 64GB,458g,4GB,12MP,12MP,A14 Bionic,7608,6.1,"PKR 79,999","INR 54,900","CNY 3,299",USD 599,"AED 2,099",2020
81,81,Apple,iPad Air 10.9-inch 256GB,458g,4GB,12MP,12MP,A14 Bionic,7608,6.1,"PKR 89,999","INR 64,900","CNY 3,699",USD 749,"AED 2,499",2020
82,82,Apple,iPad 10.2-inch 32GB,490g,3GB,12MP,8MP,A13 Bionic,8612,6.1,"PKR 49,999","INR 29,900","CNY 2,299",USD 329,"AED 1,199",2020
83,83,Apple,iPad 10.2-inch 128GB,490g,3GB,12MP,8MP,A13 Bionic,8612,6.1,"PKR 59,999","INR 39,900","CNY 2,699",USD 429,"AED 1,499",2020
84,84,Apple,iPad Mini 7.9-inch 64GB,300.5g,3GB,7MP,8MP,A12 Bionic,5124,6.1,"PKR 69,999","INR 39,900","CNY 3,499",USD 399,"AED 1,499",2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
920,920,POCO,F6 Pro 256GB,210g,8GB,20MP,108MP,Snapdragon 8+ Gen 2,5160,6.1,"PKR 109,999","INR 44,999","CNY 3,499",USD 549,"AED 1,999",2024
923,923,POCO,X7 Pro 256GB,207g,8GB,20MP,108MP,MediaTek Dimensity 8400,6000,6.1,"PKR 79,999","INR 27,999","CNY 2,699",USD 399,"AED 1,499",2025
924,924,POCO,M7 5G 128GB,198g,6GB,8MP,50MP,MediaTek Dimensity 7025,5110,6.1,"PKR 39,999","INR 15,999","CNY 1,599",USD 229,AED 899,2024
925,925,Poco,Pad 5G 128GB,571g,8GB,8MP,8MP,Snapdragon 7s Gen 2,10000,6.1,"PKR 66,220","INR 23,999","CNY 2,099",USD 280,"AED 1,029",2024
926,926,Poco,Pad 5G 256GB,571g,8GB,8MP,8MP,Snapdragon 7s Gen 2,10000,6.1,"PKR 71,220","INR 25,999","CNY 2,299",USD 300,"AED 1,099",2024

In [218]:
# Find phones with screen size larger than 6.5 inches.
df["Screen Size"].dtype

dtype('float64')

In [224]:
# 15. Find phones with screen size larger than 6.5 inches.
df[df["Screen Size"]<=6.5]

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
0,0,Apple,iPhone 16 128GB,174g,6GB,12MP,48MP,A17 Bionic,3600,6.1,"PKR 224,999","INR 79,999","CNY 5,799",USD 799,"AED 2,799",2024
1,1,Apple,iPhone 16 256GB,174g,6GB,12MP,48MP,A17 Bionic,3600,6.1,"PKR 234,999","INR 84,999","CNY 6,099",USD 849,"AED 2,999",2024
2,2,Apple,iPhone 16 512GB,174g,6GB,12MP,48MP,A17 Bionic,3600,6.1,"PKR 244,999","INR 89,999","CNY 6,499",USD 899,"AED 3,199",2024
3,3,Apple,iPhone 16 Plus 128GB,203g,6GB,12MP,48MP,A17 Bionic,4200,6.1,"PKR 249,999","INR 89,999","CNY 6,199",USD 899,"AED 3,199",2024
4,4,Apple,iPhone 16 Plus 256GB,203g,6GB,12MP,48MP,A17 Bionic,4200,6.1,"PKR 259,999","INR 94,999","CNY 6,499",USD 949,"AED 3,399",2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
925,925,Poco,Pad 5G 128GB,571g,8GB,8MP,8MP,Snapdragon 7s Gen 2,10000,6.1,"PKR 66,220","INR 23,999","CNY 2,099",USD 280,"AED 1,029",2024
926,926,Poco,Pad 5G 256GB,571g,8GB,8MP,8MP,Snapdragon 7s Gen 2,10000,6.1,"PKR 71,220","INR 25,999","CNY 2,299",USD 300,"AED 1,099",2024
927,927,Samsung,Galaxy Z Fold6 256GB,239g,12GB,"10MP, 4MP (UDC)",50MP,Snapdragon 8 Gen 3,4400,6.1,"PKR 604,999","INR 164,999","Â¥13,999","USD 1,899","AED 7,199",2024
928,928,Samsung,Galaxy Z Fold6 512GB,239g,12GB,"10MP, 4MP (UDC)",50MP,Snapdragon 8 Gen 3,4400,6.1,"PKR 544,999","INR 176,999","CNY 15,999",USD 1719,"AED 7,699",2024
929,929,Samsung,Galaxy Z Fold6 1TB,239g,12GB,"10MP, 4MP (UDC)",50MP,Snapdragon 8 Gen 3,4400,6.1,Not available,"INR 200,999","CNY 17,999Â","USD 2,259","AED 8,699",2024

In [235]:
# Find phones costing more than ₹50,000 in India.
df[df["Launched Price (India)"]<50000]

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
82,82,Apple,iPad 10.2-inch 32GB,490g,3GB,12MP,8MP,A13 Bionic,8612,6.1,"PKR 49,999",29900,"CNY 2,299",USD 329,"AED 1,199",2020
83,83,Apple,iPad 10.2-inch 128GB,490g,3GB,12MP,8MP,A13 Bionic,8612,6.1,"PKR 59,999",39900,"CNY 2,699",USD 429,"AED 1,499",2020
84,84,Apple,iPad Mini 7.9-inch 64GB,300.5g,3GB,7MP,8MP,A12 Bionic,5124,6.1,"PKR 69,999",39900,"CNY 3,499",USD 399,"AED 1,499",2019
85,85,Apple,iPad Mini 7.9-inch 256GB,300.5g,3GB,7MP,8MP,A12 Bionic,5124,6.1,"PKR 79,999",49900,"CNY 3,799",USD 499,"AED 1,799",2019
123,123,Samsung,Galaxy A54 128GB,189g,6GB,32MP,50MP + 12MP,Exynos 1380,5000,6.1,"PKR 85,000",27999,"CNY 2,199",USD 399,"AED 1,399",2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922,922,POCO,X7 128GB,195g,6GB,16MP,64MP,MediaTek Dimensity 8200,5000,6.1,"PKR 64,999",22999,"CNY 2,199",USD 329,"AED 1,199",2025
923,923,POCO,X7 Pro 256GB,207g,8GB,20MP,108MP,MediaTek Dimensity 8400,6000,6.1,"PKR 79,999",27999,"CNY 2,699",USD 399,"AED 1,499",2025
924,924,POCO,M7 5G 128GB,198g,6GB,8MP,50MP,MediaTek Dimensity 7025,5110,6.1,"PKR 39,999",15999,"CNY 1,599",USD 229,AED 899,2024
925,925,Poco,Pad 5G 128GB,571g,8GB,8MP,8MP,Snapdragon 7s Gen 2,10000,6.1,"PKR 66,220",23999,"CNY 2,099",USD 280,"AED 1,029",2024
926,926,Poco,Pad 5G 256GB,571g,8GB,8MP,8MP,Snapdragon 7s Gen 2,10000,6.1,"PKR 71,220",25999,"CNY 2,299",USD 300,"AED 1,099",2024

In [236]:
# Find phones costing less than ₹20,000 in India.
df[df["Launched Price (India)"]>20000]

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
0,0,Apple,iPhone 16 128GB,174g,6GB,12MP,48MP,A17 Bionic,3600,6.1,"PKR 224,999",79999,"CNY 5,799",USD 799,"AED 2,799",2024
1,1,Apple,iPhone 16 256GB,174g,6GB,12MP,48MP,A17 Bionic,3600,6.1,"PKR 234,999",84999,"CNY 6,099",USD 849,"AED 2,999",2024
2,2,Apple,iPhone 16 512GB,174g,6GB,12MP,48MP,A17 Bionic,3600,6.1,"PKR 244,999",89999,"CNY 6,499",USD 899,"AED 3,199",2024
3,3,Apple,iPhone 16 Plus 128GB,203g,6GB,12MP,48MP,A17 Bionic,4200,6.1,"PKR 249,999",89999,"CNY 6,199",USD 899,"AED 3,199",2024
4,4,Apple,iPhone 16 Plus 256GB,203g,6GB,12MP,48MP,A17 Bionic,4200,6.1,"PKR 259,999",94999,"CNY 6,499",USD 949,"AED 3,399",2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
925,925,Poco,Pad 5G 128GB,571g,8GB,8MP,8MP,Snapdragon 7s Gen 2,10000,6.1,"PKR 66,220",23999,"CNY 2,099",USD 280,"AED 1,029",2024
926,926,Poco,Pad 5G 256GB,571g,8GB,8MP,8MP,Snapdragon 7s Gen 2,10000,6.1,"PKR 71,220",25999,"CNY 2,299",USD 300,"AED 1,099",2024
927,927,Samsung,Galaxy Z Fold6 256GB,239g,12GB,"10MP, 4MP (UDC)",50MP,Snapdragon 8 Gen 3,4400,6.1,"PKR 604,999",164999,"Â¥13,999","USD 1,899","AED 7,199",2024
928,928,Samsung,Galaxy Z Fold6 512GB,239g,12GB,"10MP, 4MP (UDC)",50MP,Snapdragon 8 Gen 3,4400,6.1,"PKR 544,999",176999,"CNY 15,999",USD 1719,"AED 7,699",2024
929,929,Samsung,Galaxy Z Fold6 1TB,239g,12GB,"10MP, 4MP (UDC)",50MP,Snapdragon 8 Gen 3,4400,6.1,Not available,200999,"CNY 17,999Â","USD 2,259","AED 8,699",2024

In [238]:
# Find phones with Snapdragon processor.
df[df["Processor"].str.contains("Snapdragon")]

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
103,103,Samsung,Galaxy S23 Ultra 128GB,228g,12GB,12MP,200MP + 12MP,Snapdragon 8 Gen 2,5000,6.1,"PKR 430,000",99900,"CNY 7,299","USD 1,199","AED 4,599",2023
104,104,Samsung,Galaxy S23 Ultra 256GB,228g,12GB,12MP,200MP + 12MP,Snapdragon 8 Gen 2,5000,6.1,"PKR 460,000",109900,"CNY 7,999","USD 1,299","AED 4,899",2023
105,105,Samsung,Galaxy S23+ 128GB,196g,8GB,12MP,50MP + 12MP,Snapdragon 8 Gen 2,4700,6.1,"PKR 360,000",79900,"CNY 6,199",USD 899,"AED 3,399",2023
106,106,Samsung,Galaxy S23+ 256GB,196g,8GB,12MP,50MP + 12MP,Snapdragon 8 Gen 2,4700,6.1,"PKR 390,000",89900,"CNY 6,799",USD 999,"AED 3,599",2023
107,107,Samsung,Galaxy S23 128GB,168g,8GB,12MP,50MP + 12MP,Snapdragon 8 Gen 2,3900,6.1,"PKR 320,000",69900,"CNY 5,499",USD 799,"AED 3,099",2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
925,925,Poco,Pad 5G 128GB,571g,8GB,8MP,8MP,Snapdragon 7s Gen 2,10000,6.1,"PKR 66,220",23999,"CNY 2,099",USD 280,"AED 1,029",2024
926,926,Poco,Pad 5G 256GB,571g,8GB,8MP,8MP,Snapdragon 7s Gen 2,10000,6.1,"PKR 71,220",25999,"CNY 2,299",USD 300,"AED 1,099",2024
927,927,Samsung,Galaxy Z Fold6 256GB,239g,12GB,"10MP, 4MP (UDC)",50MP,Snapdragon 8 Gen 3,4400,6.1,"PKR 604,999",164999,"Â¥13,999","USD 1,899","AED 7,199",2024
928,928,Samsung,Galaxy Z Fold6 512GB,239g,12GB,"10MP, 4MP (UDC)",50MP,Snapdragon 8 Gen 3,4400,6.1,"PKR 544,999",176999,"CNY 15,999",USD 1719,"AED 7,699",2024
929,929,Samsung,Galaxy Z Fold6 1TB,239g,12GB,"10MP, 4MP (UDC)",50MP,Snapdragon 8 Gen 3,4400,6.1,Not available,200999,"CNY 17,999Â","USD 2,259","AED 8,699",2024

In [239]:
# Find phones with MediaTek processor.
df[df["Processor"].str.contains("MediaTek")]

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
125,125,Samsung,Galaxy A34 128GB,199g,6GB,13MP,48MP + 8MP,MediaTek Dimensity 1080,5000,6.1,"PKR 75,000",22999,"CNY 1,799",USD 349,"AED 1,299",2023
126,126,Samsung,Galaxy A34 256GB,199g,6GB,13MP,48MP + 8MP,MediaTek Dimensity 1080,5000,6.1,"PKR 85,000",27999,"CNY 1,999",USD 399,"AED 1,399",2023
127,127,Samsung,Galaxy A24 128GB,195g,6GB,13MP,50MP + 5MP,MediaTek Helio G99,5000,6.1,"PKR 70,000",19999,"CNY 1,599",USD 299,"AED 1,199",2023
128,128,Samsung,Galaxy A24 256GB,195g,6GB,13MP,50MP + 5MP,MediaTek Helio G99,5000,6.1,"PKR 80,000",24999,"CNY 1,799",USD 349,"AED 1,299",2023
139,139,Samsung,Galaxy M04 64GB,188g,4GB,5MP,13MP + 2MP,MediaTek Helio P35,5000,6.1,"PKR 50,000",12999,"CNY 1,099",USD 199,AED 899,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
918,918,POCO,X6 Pro 256GB,205g,8GB,20MP,108MP,MediaTek Dimensity 8300,5000,6.1,"PKR 69,999",24999,"CNY 2,599",USD 399,"AED 1,499",2024
921,921,POCO,C65 64GB,190g,4GB,5MP,50MP,MediaTek Helio G85,5000,6.1,"PKR 24,999",10999,CNY 999,USD 149,AED 599,2024
922,922,POCO,X7 128GB,195g,6GB,16MP,64MP,MediaTek Dimensity 8200,5000,6.1,"PKR 64,999",22999,"CNY 2,199",USD 329,"AED 1,199",2025
923,923,POCO,X7 Pro 256GB,207g,8GB,20MP,108MP,MediaTek Dimensity 8400,6000,6.1,"PKR 79,999",27999,"CNY 2,699",USD 399,"AED 1,499",2025
924,924,POCO,M7 5G 128GB,198g,6GB,8MP,50MP,MediaTek Dimensity 7025,5110,6.1,"PKR 39,999",15999,"CNY 1,599",USD 229,AED 899,2024

In [248]:
df["Back Camera"] = df["Back Camera"].str.replace("MP","")

In [252]:
# Find phones Back Camera with 108MP back camera.
df[df["Back Camera"].str.contains("108")]

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
109,109,Samsung,Galaxy S22 Ultra 128GB,228g,12GB,10MP,108 + 12,Exynos 2200,5000,6.1,"PKR 420,000",94900,"CNY 6,599","USD 1,099","AED 4,499",2022
110,110,Samsung,Galaxy S22 Ultra 256GB,228g,12GB,10MP,108 + 12,Exynos 2200,5000,6.1,"PKR 450,000",104900,"CNY 7,199","USD 1,199","AED 4,799",2022
133,133,Samsung,Galaxy M54 128GB,202g,8GB,32MP,108 + 8,Exynos 1380,6000,6.1,"PKR 95,000",23999,"CNY 2,099",USD 349,"AED 1,299",2023
134,134,Samsung,Galaxy M54 256GB,202g,8GB,32MP,108 + 8,Exynos 1380,6000,6.1,"PKR 105,000",26999,"CNY 2,299",USD 399,"AED 1,399",2023
141,141,Samsung,Galaxy F54 128GB,199g,8GB,32MP,108 + 8,Exynos 1380,6000,6.1,"PKR 85,000",23999,"CNY 2,199",USD 349,"AED 1,299",2023
142,142,Samsung,Galaxy F54 256GB,199g,8GB,32MP,108 + 8,Exynos 1380,6000,6.1,"PKR 95,000",26999,"CNY 2,399",USD 399,"AED 1,399",2023
147,147,Samsung,Galaxy Note 20 Ultra 128GB,208g,12GB,10MP,108 + 12,Exynos 990,4500,6.1,"PKR 180,000",99999,"CNY 7,999","USD 1,299","AED 4,499",2020
148,148,Samsung,Galaxy Note 20 Ultra 256GB,208g,12GB,10MP,108 + 12,Exynos 990,4500,6.1,"PKR 200,000",104999,"CNY 8,499","USD 1,399","AED 4,999",2020
149,149,Samsung,Galaxy Note 20 128GB,192g,8GB,10MP,108 + 12,Exynos 990,4300,6.1,"PKR 150,000",77999,"CNY 6,499",USD 999,"AED 3,999",2020
150,150,Samsung,Galaxy Note 20 256GB,192g,8GB,10MP,108 + 12,Exynos 990,4300,6.1,"PKR 170,000",89999,"CNY 7,099","USD 1,099","AED 4,199",2020
164,164,Samsung,Galaxy W22 5G 256GB,228g,12GB,10MP,108 + 12,Snapdragon 888,4500,6.1,"PKR 280,000",99999,"CNY 10,999","USD 1,499","AED 5,499",2021
165,165,Samsung,Galaxy W21 5G 256GB,229g,12GB,10MP,108 + 12,Snapdragon 888,4500,6.1,"PKR 260,000",89999,"CNY 9,999","USD 1,399","AED 4,999",2020
188,188,OnePlus,OnePlus Nord CE 3 Lite 128GB,195g,8GB,16MP,108,Snapdragon 695,5000,6.1,"PKR 59,999",17999,"CNY 2,099",USD 299,"AED 1,199",2023
244,244,Vivo,S18 Pro 256GB,189g,12GB,32MP,108,Snapdragon 8 Gen 2,4700,6.1,"PKR 99,999",59999,"CNY 3,999",USD 599,"AED 2,199",2024
423,423,Oppo,K11x 128GB,195g,8GB,16MP,108 + 2,Qualcomm Snapdragon 695,5000,6.1,"PKR 59,999",18000,"CNY 1,499",USD 199,"AED 1,000",2023
424,424,Oppo,K11x 256GB,195g,12GB,16MP,108 + 2,Qualcomm Snapdragon 695,5000,6.1,"PKR 64,999",20000,"CNY 1,699",USD 229,"AED 1,200",2023
437,437,Oppo,K11x 128GB,195g,8GB,16MP,108 + 2,Qualcomm Snapdragon 695,5000,6.1,"PKR 59,999",18000,"CNY 1,499",USD 199,"AED 1,000",2023
438,438,Oppo,K11x 256GB,195g,12GB,16MP,108 + 2,Qualcomm Snapdragon 695,5000,6.1,"PKR 64,999",20000,"CNY 1,699",USD 229,"AED 1,200",2023
539,539,Xiaomi,Redmi Note 14 Pro 5G 128GB,195g,8GB,16MP,108 (Main) + 8 (Ultra-wide) + 2 (Macro),MediaTek Dimensity 7300-Ultra,5500,6.1,"PKR 79,999",27999,"CNY 2,199",USD 349.00,"AED 1,399",2024
540,540,Xiaomi,Redmi Note 14 Pro 5G 256GB,195g,12GB,16MP,108 (Main) + 8 (Ultra-wide) + 2 (Macro),MediaTek Dimensity 7300-Ultra,5500,6.1,"PKR 89,999",30999,"CNY 2,499",USD 379.00,"AED 1,499",2024
541,541,Xiaomi,Redmi Note 14 Pro 4G 128GB,190g,6GB,16MP,108 (Main) + 8 (Ultra-wide) + 2 (Macro),Qualcomm Snapdragon 732G,5000,6.1,"PKR 69,999",24999,"CNY 1,999",USD 299.00,"AED 1,199",2024
542,542,Xiaomi,Redmi Note 14 Pro 4G 256GB,190g,8GB,16MP,108 (Main) + 8 (Ultra-wide) + 2 (Macro),Qualcomm Snapdragon 732G,5000,6.1,"PKR 79,999",27999,"CNY 2,299",USD 329.00,"AED 1,299",2024
639,639,Huawei,Nova 10 SE,184g,8GB,16MP,108,Snapdragon 680 4G,4500,6.1,"PKR 79,999",34999,"CNY 2,299",USD 399,"AED 1,499",2022
724,724,Tecno,Camon 30S Pro 512GB,202g,12GB,50MP,108,MediaTek Dimensity 9200,5200,6.1,"PKR 159,999",79999,"CNY 6,999","USD 1,099","AED 4,199",2024
728,728,Tecno,Camon 30 Premier 512GB,210g,12GB,50MP,108,MediaTek Dimensity 9200,5200,6.1,"PKR 179,999",89999,"CNY 7,499","USD 1,199","AED 4,499",2024
739,739,Tecno,Camon 20s Pro 5G 512GB,202g,12GB,50MP,108,MediaTek Dimensity 9200,5200,6.1,"PKR 159,999",79999,"CNY 6,999","USD 1,099","AED 4,199",2024
740,740,Tecno,Camon 20s Pro 256GB,202g,12GB,50MP,108,MediaTek Dimensity 810,5200,6.1,"PKR 129,999",59999,"CNY 4,999",USD 899,"AED 3,499",2024
742,742,Tecno,Camon 20 Premier 512GB,205g,12GB,50MP,108,MediaTek Dimensity 8200,5200,6.1,"PKR 149,999",74999,"CNY 6,499","USD 1,049","AED 3,999",2024
756,756,Infinix,Hot 50 Pro+,196g,12GB,32MP,108,MediaTek Dimensity 9200,5300,6.1,"PKR 64,999",24999,"CNY 2,499",USD 379,"AED 1,399",2024
757,757,Infinix,GT 20 Pro,198g,12GB,32MP,108,MediaTek Dimensity 8200,5500,6.1,"PKR 89,999",32999,"CNY 2,999",USD 449,"AED 1,699",2024
758,758,Infinix,Note 40X 5G,198g,8GB,32MP,108,MediaTek Dimensity 7200,5200,6.1,"PKR 64,999",23999,"CNY 2,299",USD 349,"AED 1,299",2024
760,760,Infinix,Note 40 5G,195g,8GB,32MP,108,MediaTek Dimensity 8100,5200,6.1,"PKR 54,999",19999,"CNY 1,999",USD 319,"AED 1,099",2024
761,761,Infinix,Note 40 Pro 5G,195g,12GB,32MP,108,MediaTek Dimensity 9000,5300,6.1,"PKR 72,999",27999,"CNY 2,499",USD 399,"AED 1,499",2024
762,762,Infinix,Note 40 Racing Edition,196g,12GB,32MP,108,MediaTek Dimensity 9200,5500,6.1,"PKR 89,999",32999,"CNY 2,999",USD 449,"AED 1,699",2024
765,765,Infinix,Hot 40 Pro,195g,8GB,32MP,108,MediaTek Helio G99,5000,6.1,"PKR 39,999",14999,"CNY 1,399",USD 229,AED 849,2023
766,766,Infinix,Zero 40,195g,12GB,50MP,108,MediaTek Dimensity 8200,5000,6.1,"PKR 69,999",24999,"CNY 2,199",USD 349,"AED 1,299",2024
767,767,Infinix,Zero 40 5G,195g,12GB,50MP,108,MediaTek Dimensity 8200,5000,6.1,"PKR 74,999",27999,"CNY 2,299",USD 379,"AED 1,399",2024
768,768,Infinix,Zero Flip,190g,8GB,32MP,108,Qualcomm Snapdragon 778G,4500,6.1,"PKR 89,999",32999,"CNY 2,499",USD 399,"AED 1,499",2024
769,769,Infinix,Note 40,190g,8GB,32MP,108,MediaTek Helio G99,5000,6.1,"PKR 45,999",17999,"CNY 1,799",USD 279,AED 999,2024
770,770,Infinix,Note 40 Pro,190g,12GB,32MP,108,MediaTek Dimensity 8100,5000,6.1,"PKR 59,999",22999,"CNY 2,199",USD 329,"AED 1,199",2024
776,776,Infinix,Zero 30 256GB,185g,8GB,50MP,108,MediaTek Dimensity 8020,5000,6.1,"PKR 69,999",26999,"CNY 2,199",USD 349,"AED 1,299",2023
777,777,Infinix,Zero 30 5G 256GB,185g,12GB,50MP,108,MediaTek Dimensity 8020,5000,6.1,"PKR 74,999",29999,"CNY 2,299",USD 379,"AED 1,399",2023
778,778,Infinix,GT 10 Pro 256GB,187g,8GB,32MP,108,MediaTek Dimensity 8050,5000,6.1,"PKR 84,999",32999,"CNY 2,599",USD 399,"AED 1,499",2023
815,815,Honor,50,175g,8GB,32MP,108,Qualcomm Snapdragon 778G,4300,6.1,"PKR 89,999",37999,"CNY 2,699",USD 549,"AED 2,049",2021
816,816,Honor,50 Pro,187g,8GB,32MP,108,Qualcomm Snapdragon 778G,4000,6.1,"PKR 109,999",44999,"CNY 3,699",USD 649,"AED 2,499",2021
817,817,Honor,50 SE,191g,8GB,16MP,108,MediaTek Dimensity 900,4000,6.1,"PKR 74,999",29999,"CNY 2,399",USD 449,"AED 1,699",2021
825,825,Honor,60,179g,8GB,32MP,108,Qualcomm Snapdragon 778G,4800,6.1,"PKR 99,999",41999,"CNY 2,699",USD 549,"AED 2,049",2021
826,826,Honor,60 Pro,192g,8GB,50MP,108,Qualcomm Snapdragon 778G+,4800,6.1,"PKR 124,999",49999,"CNY 3,699",USD 649,"AED 2,599",2021
851,851,Honor,X50,185g,6GB,8MP,108,Qualcomm Snapdragon 6 Gen 1,5800,6.1,"PKR 74,999",28999,"CNY 1,599",USD 299,"AED 1,099",2023
862,862,Honor,X60,185g,6GB,8MP,108,Qualcomm Snapdragon 6 Gen 1,5800,6.1,"PKR 74,999",28999,"CNY 1,599",USD 299,"AED 1,099",2023
907,907,POCO,X4 Pro 5G 128GB,205g,6GB,16MP,108,Snapdragon 695,5000,6.1,"PKR 54,999",18999,"CNY 1,999",USD 299,"AED 1,199",2022
914,914,POCO,X5 Pro 128GB,181g,6GB,16MP,108,Snapdragon 778G,5000,6.1,"PKR 64,999",22999,"CNY 2,199",USD 329,"AED 1,199",2023
918,918,POCO,X6 Pro 256GB,205g,8GB,20MP,108,MediaTek Dimensity 8300,5000,6.1,"PKR 69,999",24999,"CNY 2,599",USD 399,"AED 1,499",2024
920,920,POCO,F6 Pro 256GB,210g,8GB,20MP,108,Snapdragon 8+ Gen 2,5160,6.1,"PKR 109,999",44999,"CNY 3,499",USD 549,"AED 1,999",2024
923,923,POCO,X7 Pro 256GB,207g,8GB,20MP,108,MediaTek Dimensity 8400,6000,6.1,"PKR 79,999",27999,"CNY 2,699",USD 399,"AED 1,499",2025

In [253]:
# Sort phones by India price ascending.
df.sort_values("Launched Price (India)")

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
796,796,Infinix,Smart HD 32GB,195g,2GB,5MP,8,MediaTek Helio A20,5000,6.1,"PKR 15,999",5999,CNY 499,USD 79,AED 299,2020
716,716,Tecno,Pop 9 64GB,190g,3GB,5MP,8,Unisoc SC9832E,5000,6.1,"PKR 21,999",6999,CNY 549,USD 89,AED 349,2024
738,738,Tecno,Pop 8 64GB,195g,3GB,5MP,8,Unisoc SC9832E,5000,6.1,"PKR 21,999",6999,CNY 549,USD 89,AED 349,2024
803,803,Infinix,Smart 5 64GB,195g,3GB,8MP,13,MediaTek Helio A20,5000,6.1,"PKR 18,999",7499,CNY 599,USD 99,AED 349,2020
711,711,Tecno,Pop 9 4G 64GB,195g,3GB,5MP,8,Unisoc SC9863A,5000,6.1,"PKR 22,999",7499,CNY 599,USD 99,AED 399,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
657,657,Huawei,Mate X6,241g,12GB,8MP,50 + 13 + 12,Kirin 9010,4800,6.1,"PKR 349,999",249999,"CNY 12,999","USD 2,499","AED 9,999",2024
630,630,Huawei,Mate X2,295g,8GB,16MP,50,Kirin 9000 5G,4500,6.1,"PKR 349,999",249999,"CNY 17,999","USD 2,699","AED 9,999",2021
643,643,Huawei,Mate X3,239g,12GB,8MP,50 (wide) + 13 (ultrawide) + 12 (periscope tel...,Snapdragon 8+ Gen 1 4G,4800,6.1,"PKR 349,999",249999,"CNY 13,999","USD 2,499","AED 9,999",2023
660,660,Huawei,Mate XT 256GB,245g,12GB,13MP,50 + 12 + 48,Kirin 9010,5000,6.1,"PKR 359,999",259999,"CNY 13,499","USD 2,599","AED 10,499",2024
661,661,Huawei,Mate XT 512GB,245g,12GB,13MP,50 + 12 + 48,Kirin 9010,5000,6.1,"PKR 389,999",274999,"CNY 14,499","USD 2,799","AED 11,099",2024

In [254]:
# Sort phones by battery descending.
df.sort_values("Battery Capacity",ascending=False)

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
166,166,Samsung,Galaxy Tab S9 Ultra 256GB,732g,12GB,12MP + 12MP,13 + 8,Snapdragon 8 Gen 2,11200,6.1,"PKR 350,000",114999,"CNY 9,999","USD 1,199","AED 4,499",2023
170,170,Samsung,Galaxy Tab S8 Ultra 256GB,726g,12GB,12MP + 12MP,13 + 6,Snapdragon 8 Gen 1,11200,6.1,"PKR 320,000",109999,"CNY 9,499","USD 1,099","AED 4,299",2022
234,234,OnePlus,OnePlus Pad Pro,610g,12GB,16MP,50,Snapdragon 8 Gen 3,11000,6.1,"PKR 169,999",69999,"CNY 5,999",USD 799,"AED 2,599",2024
893,893,Honor,MagicPad 3,590g,12GB,12MP,16,Qualcomm Snapdragon 8 Gen 3,10500,6.1,"PKR 149,999",64999,"CNY 3,999",USD 799,"AED 2,999",2024
885,885,Honor,MagicPad 2,580g,16GB,12MP,16,Qualcomm Snapdragon 8 Gen 2,10500,6.1,"PKR 179,999",74999,"CNY 4,499",USD 899,"AED 3,299",2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,251,Vivo,X5Max 16GB,146g,2GB,5MP,13,Snapdragon 615,2300,6.1,"PKR 29,999",16999,"CNY 1,299",USD 199,AED 699,2014
49,49,Apple,iPhone 12 mini 128GB,135g,4GB,12MP,12,A14 Bionic,2227,6.1,"PKR 184,999",74900,"CNY 5,599",USD 799,"AED 2,999",2020
48,48,Apple,iPhone 12 mini 64GB,135g,4GB,12MP,12,A14 Bionic,2227,6.1,"PKR 174,999",69900,"CNY 5,199",USD 699,"AED 2,599",2020
50,50,Apple,iPhone 12 mini 256GB,135g,4GB,12MP,12,A14 Bionic,2227,6.1,"PKR 194,999",84900,"CNY 5,999",USD 899,"AED 3,299",2020
255,255,Vivo,X3S 16GB,153g,1GB,5MP,13,MediaTek MT6592,2000,6.1,"PKR 19,999",10999,CNY 899,USD 139,AED 499,2014

In [257]:
# Find top 10 expensive phones in India.
df.sort_values("Launched Price (India)",ascending=False).head(10)

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
661,661,Huawei,Mate XT 512GB,245g,12GB,13MP,50 + 12 + 48,Kirin 9010,5000,6.1,"PKR 389,999",274999,"CNY 14,499","USD 2,799","AED 11,099",2024
660,660,Huawei,Mate XT 256GB,245g,12GB,13MP,50 + 12 + 48,Kirin 9010,5000,6.1,"PKR 359,999",259999,"CNY 13,499","USD 2,599","AED 10,499",2024
643,643,Huawei,Mate X3,239g,12GB,8MP,50 (wide) + 13 (ultrawide) + 12 (periscope tel...,Snapdragon 8+ Gen 1 4G,4800,6.1,"PKR 349,999",249999,"CNY 13,999","USD 2,499","AED 9,999",2023
657,657,Huawei,Mate X6,241g,12GB,8MP,50 + 13 + 12,Kirin 9010,4800,6.1,"PKR 349,999",249999,"CNY 12,999","USD 2,499","AED 9,999",2024
630,630,Huawei,Mate X2,295g,8GB,16MP,50,Kirin 9000 5G,4500,6.1,"PKR 349,999",249999,"CNY 17,999","USD 2,699","AED 9,999",2021
929,929,Samsung,Galaxy Z Fold6 1TB,239g,12GB,"10MP, 4MP (UDC)",50,Snapdragon 8 Gen 3,4400,6.1,Not available,200999,"CNY 17,999Â","USD 2,259","AED 8,699",2024
634,634,Huawei,Mate Xs 2,255g,8GB,10.7MP,50,Snapdragon 888 4G,4600,6.1,"PKR 299,999",199999,"CNY 14,999","USD 2,499","AED 8,999",2022
96,96,Apple,iPad Pro 13-inch 2TB,708g,6GB,7MP,12 + 10,A12Z Bionic,10307,6.1,"PKR 399,999",199900,"CNY 11,199","USD 1,799","AED 6,099",2020
708,708,Google,Pixel 9 Pro Fold 512GB,250g,16GB,10.8MP,50,Google Tensor G4,5500,6.1,"PKR 399,999",179999,"CNY 13,999","USD 1,799","AED 6,999",2024
95,95,Apple,iPad Pro 13-inch 1TB,708g,6GB,7MP,12 + 10,A12Z Bionic,10307,6.1,"PKR 359,999",179900,"CNY 10,399","USD 1,599","AED 5,799",2020

In [260]:
# Find top 5 cheapest phones in USA.
df["Launched Price (USA)"] = df["Launched Price (USA)"].str.replace("USD","").str.replace(",","").astype(float)

In [263]:
df.sort_values("Launched Price (USA)").head(5)

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
796,796,Infinix,Smart HD 32GB,195g,2GB,5MP,8,MediaTek Helio A20,5000,6.1,"PKR 15,999",5999,CNY 499,79.0,AED 299,2020
716,716,Tecno,Pop 9 64GB,190g,3GB,5MP,8,Unisoc SC9832E,5000,6.1,"PKR 21,999",6999,CNY 549,89.0,AED 349,2024
738,738,Tecno,Pop 8 64GB,195g,3GB,5MP,8,Unisoc SC9832E,5000,6.1,"PKR 21,999",6999,CNY 549,89.0,AED 349,2024
711,711,Tecno,Pop 9 4G 64GB,195g,3GB,5MP,8,Unisoc SC9863A,5000,6.1,"PKR 22,999",7499,CNY 599,99.0,AED 399,2024
723,723,Tecno,Spark Go 1 64GB,195g,3GB,5MP,8,Unisoc SC9863A,5000,6.1,"PKR 22,999",7499,CNY 599,99.0,AED 399,2024

In [264]:
# Find average India launch price.
df["Launched Price (India)"].mean()

np.float64(50576.818279569896)

In [268]:
# Find maximum battery capacity.
df[df["Battery Capacity"] == df["Battery Capacity"].max()]

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
166,166,Samsung,Galaxy Tab S9 Ultra 256GB,732g,12GB,12MP + 12MP,13 + 8,Snapdragon 8 Gen 2,11200,6.1,"PKR 350,000",114999,"CNY 9,999",1199.0,"AED 4,499",2023
170,170,Samsung,Galaxy Tab S8 Ultra 256GB,726g,12GB,12MP + 12MP,13 + 6,Snapdragon 8 Gen 1,11200,6.1,"PKR 320,000",109999,"CNY 9,499",1099.0,"AED 4,299",2022

In [269]:
# Find minimum battery capacity.
df[df["Battery Capacity"] == df["Battery Capacity"].min()]

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
255,255,Vivo,X3S 16GB,153g,1GB,5MP,13,MediaTek MT6592,2000,6.1,"PKR 19,999",10999,CNY 899,139.0,AED 499,2014

In [270]:
# Find average screen size.
df["Screen Size"].mean()

np.float64(6.099999999999999)

In [273]:
# Find average phone weight.
df["Mobile Weight"] = df["Mobile Weight"].str.replace("g","").astype(float)

In [274]:
df["Mobile Weight"].mean()

np.float64(228.26709677419356)

In [279]:
# Count phones company-wise.
df.groupby("Company Name")["Company Name"].value_counts()

Company Name
Apple        97
Google       21
Honor        91
Huawei       42
Infinix      56
Lenovo       15
Motorola     62
Nokia        11
OnePlus      53
Oppo        129
POCO         30
Poco          2
Realme       69
Samsung      88
Sony          9
Tecno        39
Vivo         86
Xiaomi       27
iQOO          3
Name: count, dtype: int64

In [281]:
# Count phones year-wise.
df.groupby("Company Name")["Launched Year"].value_counts()

Company Name  Launched Year
Apple         2020             27
              2024             12
              2023             12
              2022             12
              2021             12
                               ..
Vivo          2016              1
Xiaomi        2024             23
              2023              4
iQOO          2024              2
              2023              1
Name: count, Length: 92, dtype: int64

In [284]:
# Find average India price company-wise.
df.groupby("Company Name")["Launched Price (India)"].mean()

Company Name
Apple       102998.597938
Google       70332.333333
Honor        48850.648352
Huawei      102798.571429
Infinix      17320.428571
Lenovo       25392.400000
Motorola     33692.548387
Nokia        13771.727273
OnePlus      45734.849057
Oppo         43758.449612
POCO         22649.000000
Poco         24999.000000
Realme       26147.652174
Samsung      63605.500000
Sony         91665.666667
Tecno        36806.692308
Vivo         35770.267442
Xiaomi       57258.259259
iQOO         43999.000000
Name: Launched Price (India), dtype: float64

In [285]:
# Find average battery company-wise.
df.groupby("Company Name")["Battery Capacity"].mean()

Company Name
Apple        4442.577320
Google       4341.047619
Honor        5488.461538
Huawei       4900.000000
Infinix      5330.357143
Lenovo       4520.000000
Motorola     4688.709677
Nokia        5309.090909
OnePlus      4840.377358
Oppo         4978.100775
POCO         5041.166667
Poco        10000.000000
Realme       5691.304348
Samsung      5119.431818
Sony         5000.000000
Tecno        5315.384615
Vivo         4678.604651
Xiaomi       5172.222222
iQOO         8040.000000
Name: Battery Capacity, dtype: float64

In [304]:
# Find most common RAM size.
df["RAM"].mode()

0    8GB
Name: RAM, dtype: str

In [302]:
# Find most common processor.
df["Processor"].mode()

0    Snapdragon 8 Gen 2
Name: Processor, dtype: str

In [306]:
# Find company with most phones.
df.groupby("Company Name")["Company Name"].value_counts().head(1)

Company Name
Apple    97
Name: count, dtype: int64

In [327]:
# Find company with highest average price.
df.groupby("Company Name")["Launched Price (India)"].mean().sort_values(ascending=False).head(1)

Company Name
Apple    102998.597938
Name: Launched Price (India), dtype: float64

In [332]:
# Find phones having both 12GB RAM
df[df["RAM"].str.contains("12GB")]

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
97,97,Samsung,Galaxy S24 Ultra 128GB,234.0,12GB,12MP,200 + 12,Exynos 2400,5000,6.1,"PKR 450,000",104900,"CNY 7,499",1199.0,"AED 4,899",2024
98,98,Samsung,Galaxy S24 Ultra 256GB,234.0,12GB,12MP,200 + 12,Exynos 2400,5000,6.1,"PKR 480,000",114900,"CNY 7,999",1299.0,"AED 5,099",2024
103,103,Samsung,Galaxy S23 Ultra 128GB,228.0,12GB,12MP,200 + 12,Snapdragon 8 Gen 2,5000,6.1,"PKR 430,000",99900,"CNY 7,299",1199.0,"AED 4,599",2023
104,104,Samsung,Galaxy S23 Ultra 256GB,228.0,12GB,12MP,200 + 12,Snapdragon 8 Gen 2,5000,6.1,"PKR 460,000",109900,"CNY 7,999",1299.0,"AED 4,899",2023
109,109,Samsung,Galaxy S22 Ultra 128GB,228.0,12GB,10MP,108 + 12,Exynos 2200,5000,6.1,"PKR 420,000",94900,"CNY 6,599",1099.0,"AED 4,499",2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890,890,Honor,Pad GT Pro,610.0,12GB,12MP,16,Qualcomm Snapdragon 8 Gen 3,10500,6.1,"PKR 199,999",84999,"CNY 4,999",999.0,"AED 3,799",2024
893,893,Honor,MagicPad 3,590.0,12GB,12MP,16,Qualcomm Snapdragon 8 Gen 3,10500,6.1,"PKR 149,999",64999,"CNY 3,999",799.0,"AED 2,999",2024
927,927,Samsung,Galaxy Z Fold6 256GB,239.0,12GB,"10MP, 4MP (UDC)",50,Snapdragon 8 Gen 3,4400,6.1,"PKR 604,999",164999,"Â¥13,999",1899.0,"AED 7,199",2024
928,928,Samsung,Galaxy Z Fold6 512GB,239.0,12GB,"10MP, 4MP (UDC)",50,Snapdragon 8 Gen 3,4400,6.1,"PKR 544,999",176999,"CNY 15,999",1719.0,"AED 7,699",2024
929,929,Samsung,Galaxy Z Fold6 1TB,239.0,12GB,"10MP, 4MP (UDC)",50,Snapdragon 8 Gen 3,4400,6.1,Not available,200999,"CNY 17,999Â",2259.0,"AED 8,699",2024

In [334]:
# Find all premium phones above ₹80,000.
df[df["Launched Price (India)"]>80000]

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
1,1,Apple,iPhone 16 256GB,174.0,6GB,12MP,48,A17 Bionic,3600,6.1,"PKR 234,999",84999,"CNY 6,099",849.0,"AED 2,999",2024
2,2,Apple,iPhone 16 512GB,174.0,6GB,12MP,48,A17 Bionic,3600,6.1,"PKR 244,999",89999,"CNY 6,499",899.0,"AED 3,199",2024
3,3,Apple,iPhone 16 Plus 128GB,203.0,6GB,12MP,48,A17 Bionic,4200,6.1,"PKR 249,999",89999,"CNY 6,199",899.0,"AED 3,199",2024
4,4,Apple,iPhone 16 Plus 256GB,203.0,6GB,12MP,48,A17 Bionic,4200,6.1,"PKR 259,999",94999,"CNY 6,499",949.0,"AED 3,399",2024
5,5,Apple,iPhone 16 Plus 512GB,203.0,6GB,12MP,48,A17 Bionic,4200,6.1,"PKR 274,999",104999,"CNY 6,999",999.0,"AED 3,599",2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
869,869,Honor,Magic V3,231.0,12GB,16MP,50,Qualcomm Snapdragon 8 Gen 2,5000,6.1,"PKR 389,999",159999,"CNY 10,999",1899.0,"AED 6,999",2024
890,890,Honor,Pad GT Pro,610.0,12GB,12MP,16,Qualcomm Snapdragon 8 Gen 3,10500,6.1,"PKR 199,999",84999,"CNY 4,999",999.0,"AED 3,799",2024
927,927,Samsung,Galaxy Z Fold6 256GB,239.0,12GB,"10MP, 4MP (UDC)",50,Snapdragon 8 Gen 3,4400,6.1,"PKR 604,999",164999,"Â¥13,999",1899.0,"AED 7,199",2024
928,928,Samsung,Galaxy Z Fold6 512GB,239.0,12GB,"10MP, 4MP (UDC)",50,Snapdragon 8 Gen 3,4400,6.1,"PKR 544,999",176999,"CNY 15,999",1719.0,"AED 7,699",2024
929,929,Samsung,Galaxy Z Fold6 1TB,239.0,12GB,"10MP, 4MP (UDC)",50,Snapdragon 8 Gen 3,4400,6.1,Not available,200999,"CNY 17,999Â",2259.0,"AED 8,699",2024

In [337]:
# Find phones launched between 2020 and 2023.
df[df["Launched Year"].between(2020,2023)]

,Unnamed: 0,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
12,12,Apple,iPhone 15 128GB,171.0,6GB,12MP,48,A16 Bionic,3200,6.1,"PKR 204,999",74999,"CNY 5,299",799.0,"AED 2,699",2023
13,13,Apple,iPhone 15 256GB,171.0,6GB,12MP,48,A16 Bionic,3200,6.1,"PKR 214,999",79999,"CNY 5,599",849.0,"AED 2,999",2023
14,14,Apple,iPhone 15 512GB,171.0,6GB,12MP,48,A16 Bionic,3200,6.1,"PKR 224,999",89999,"CNY 5,999",949.0,"AED 3,199",2023
15,15,Apple,iPhone 15 Plus 128GB,203.0,6GB,12MP,48,A16 Bionic,4300,6.1,"PKR 234,999",84999,"CNY 5,699",899.0,"AED 3,199",2023
16,16,Apple,iPhone 15 Plus 256GB,203.0,6GB,12MP,48,A16 Bionic,4300,6.1,"PKR 244,999",94999,"CNY 6,199",999.0,"AED 3,399",2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912,912,POCO,F5 Pro 256GB,204.0,8GB,20MP,64,Snapdragon 8+ Gen 1,5160,6.1,"PKR 99,999",39999,"CNY 3,299",499.0,"AED 1,899",2023
913,913,POCO,X5 128GB,189.0,6GB,13MP,48,Snapdragon 695,5000,6.1,"PKR 54,999",18999,"CNY 1,799",279.0,"AED 1,099",2023
914,914,POCO,X5 Pro 128GB,181.0,6GB,16MP,108,Snapdragon 778G,5000,6.1,"PKR 64,999",22999,"CNY 2,199",329.0,"AED 1,199",2023
915,915,POCO,M6 64GB,199.0,4GB,8MP,50,MediaTek Helio G88,5000,6.1,"PKR 29,999",12999,"CNY 1,299",199.0,AED 799,2023
916,916,POCO,M6 Pro 128GB,202.0,6GB,8MP,50,Snapdragon 4 Gen 1,5000,6.1,"PKR 34,999",14999,"CNY 1,499",219.0,AED 849,2023

In [338]:
# Create a new column called `"Price Category"`:

# * Budget
# * Mid-Range
# * Premium
df["Price Category"] = df[
    "Launched Price (India)"
].apply(
    lambda x:
    "Budget" if x < 20000
    else "Mid-Range" if x < 50000
    else "Premium"
)

In [359]:
# Find percentage of premium phones.
total = df["Price Category"].value_counts().sum()

premium = df["Price Category"].value_counts()["Premium"]

percentage = (premium / total) * 100

percentage

np.float64(34.946236559139784)

In [360]:
# Compare India and USA prices.
df["Launched Price (India)"] - (df["Launched Price (USA)"]*89)

0       8888.0
1       9438.0
2       9988.0
3       9988.0
4      10538.0
        ...
925     -921.0
926     -701.0
927    -4012.0
928    24008.0
929      -52.0
Length: 930, dtype: float64

In [362]:
# Find correlation between battery and price.
df[["Battery Capacity", "Launched Price (India)"]].corr()

                        Battery Capacity  Launched Price (India)
Battery Capacity                1.000000               -0.007829
Launched Price (India)         -0.007829                1.000000

In [363]:
# Find correlation between screen size and price.
df[["Screen Size","Launched Price (India)"]].corr()

                        Screen Size  Launched Price (India)
Screen Size                     NaN                     NaN
Launched Price (India)          NaN                     1.0

In [ ]:
# Find which company gives highest battery at lowest price.